---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/packages/bounce"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/packages/bounce-macros"
    schedule:
      interval: "weekly"
