[workspace]
members = [
    "packages/bounce",
    "packages/bounce-macros",

    "examples/notion",
    "examples/simple",
    "examples/partial-render",
    "examples/random-uuid",
]
resolver = "2"
