[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

### Lints ###

# cargo clippy --all-targets --release -- --deny=warnings
# Lints --release profile
[tasks.release-lint]
private = true
command = "cargo"
args = ["clippy", "--all-targets", "--release", "--", "--deny=warnings"]

# env RUSTFLAG="--cfg releasing" cargo clippy --all-targets -- --deny=warnings
# Lints --cfg releasing flag
[tasks.releasing-lint]
private = true
command = "cargo"
args = ["clippy", "--all-targets", "--", "--deny=warnings"]

[tasks.releasing-lint.env]
RUSTFLAG = "--cfg releasing"

# cargo fmt --all -- --check
[tasks.fmt-lint]
private = true
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

# Each workspace member needs to be checked separately so that
# feature flags will not be merged.
[tasks.lints.run_task]
name = ["fmt-lint", "release-lint", "releasing-lint"]
fork = true

### Tests ###

# wasm-pack test --headless --firefox
[tasks.wasm-test]
private = true
workspace = true
command = "wasm-pack"
args = ["test", "--headless", "--firefox"]

# wasm-pack test --headless --firefox --all-features
[tasks.wasm-test-all-features]
private = true
workspace = true
command = "wasm-pack"
args = ["test", "--headless", "--firefox", "--all-features"]

# cargo test
[tasks.native-test]
private = true
workspace = true
command = "cargo"
args = ["test"]

# cargo test --all-features
[tasks.native-test-all-features]
private = true
workspace = true
command = "cargo"
args = ["test", "--all-features"]

# cargo test --doc --all-features
[tasks.doc-test]
private = true
workspace = false
command = "cargo"
args = ["test", "--doc", "--all-features", "--workspace"]

# Each workspace member needs to be tested separately so that
# feature flags will not be merged.
[tasks.tests]
workspace = false

[tasks.tests.run_task]
name = ["wasm-test", "wasm-test-all-features", "native-test", "native-test-all-features", "doc-test"]
fork = true
