[package]
name = "bounce"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/futursolo/bounce"
authors = [
    "Kaede Hoshiakwa <futursolo@icloud.com>",
]
description = "The uncomplicated state management library for Yew."
keywords = ["web", "wasm", "yew", "state-management"]
categories = ["wasm", "web-programming"]
readme = "../../README.md"
homepage = "https://github.com/futursolo/bounce"
license = "MIT OR Apache-2.0"

[dependencies]
anymap2 = "0.13.0"
once_cell = "1.8.0"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
yew = "0.19.3"
bounce-macros = { path = "../bounce-macros" }

[dev-dependencies.web-sys]
version = "0.3.54"
features = [
    "HtmlInputElement",
]
