[package]
name = "bounce"
version = "0.1.0"
edition = "2021"

[dependencies]
anymap2 = "0.13.0"
once_cell = "1.8.0"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
yew = "0.19.3"
bounce-macros = { path = "../bounce-macros" }

[dev-dependencies.web-sys]
version = "0.3.54"
features = [
    "HtmlInputElement",
]
